---
# tasks file for UpdateSystem
- name: config /etc/yum.conf
  lineinfile:
    dest: /etc/yum.conf
    relexp: '^exclude'
    line: |
      exclude=kernel*
      exclude=kernel-*
      exclude=centos-release*

- name: yum update
  shell: yum update --exclude=kernel-* -y
  retries: 3
  delay: 5

#- command: /opt/application/upgrade_db.py
#  run_once: true
#  delegate_to: web01.example.org

- name: kernel update
  shell: sleep 3 ;shutdown -r now "Ansible update triggered"
  async: 1
  poll: 0
  ignore_errors: true

- name: Waiting for server to come back
  local_action: wait_for host={{ ansible_host }} port=22 state=started delay=20 timeout=600
  become: no