---
# tasks file for SetYum
- name: find /etc/yum.repos.d/
  find:
    paths: /etc/yum.repos.d
  register: files_to_delete

- name: delete /etc/yum.repos.d/file
  file:
     path: "{{ item.path }}"
     state: absent
  with_items:
    - "{{ files_to_delete.files }}"


- name: copy yum sources to /etc/yum.repos.d/
  copy: src=files/repo/{{ item.src }} dest=/etc/yum.repos.d/{{ item.dest }}
  with_items:
    - { src: 'Centos-Base.repo.j2', dest: 'Centos-Base.repo' }
    - { src: 'ceph.repo.j2', dest: 'ceph.repo' }
    - { src: 'epel.repo.j2', dest: 'epel.repo' }


- name: yum repolist
  command: yum repolist
  register: result
- debug:
    msg: "{{ result }}"
