---
- name: add ip to conf
  lineinfile:
    dest: /home/Cephx/myceph/ceph.conf
    line: |
      public_network = {{ hostvars[ansible_hostname].[ 'ansible_' + ansible_ceph_pub_interface ].ipv4.network }}/24
      cluster_network = {{ hostvars[ansible_hostname].[ 'ansible_' + ansible_ceph_stor_interface ].ipv4.network }}/24
  when: "inventory_hostname in groups.ADMIN"