---
- name: create a directory myceph
  file:
    path: /home/Cephx/myceph
    state: directory
    mode: 0755

- name: init cluster ceph new
  command: "{{ item }}"
    chdir: /home/Cephx/myceph
  with_items:
    - "ceph-deploy new {{ ((groups.OSD + groups.MON) | unique) | join(' ') }}"
    - "ceph-deploy install {{ ((groups.OSD + groups.MON) | unique) | join(' ') }} --no-adjust-repos"
    - "ceph-deploy mon create-initial"

  retries: 3
  delay: 5
  when: "inventory_hostname in groups.ADMIN"

