---
- name: Sync config to all cluster
  shell: cd /home/Cephx/myceph/ && ceph-deploy --overwrite-conf admin {{ ((groups.OSD + groups.MON) | unique) | join(' ') }}

  when: "inventory_hostname in groups.ADMIN"