---
- name: register hosts
  set_fact:
    hosts: "{{ groups.all| unique | list }}"

- name: change name
  shell: hostnamectl set-hostname {{inventory_hostname}}



##/etc/hosts 中添加组的的ip和主机名称对应表
- name: set /etc/hosts all ip and hostname
  lineinfile:
    dest: /etc/hosts
    regexp: '^{{ hostvars[item].ansible_host }}'
    state: absent
    line: |
      {{ hostvars[item].ansible_host }} {{ item }}
#可以这样写
#        line: "{{ hostvars[item].ansible_host }} {{ item }}"
  with_items: "{{ hosts }}"



